# Generated by Django 4.0.4 on 2022-06-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_task_completed_at_task_completed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day_of_week',
            field=models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('Th', 'Thursday'), ('F', 'Friday'), ('Sa', 'Saturday'), ('Sa', 'Sunday')], max_length=15, null=True, verbose_name='День недели'),
        ),
    ]
